### ISSUE TITLE
Config your database

### ISSUE THREAD

**Issue by LeAnhTuan0810** [juzaweb/mymocms#81]
I can't find Config your database
and when i use the command **_php artisan mymo:install_** it says **Could not open input file: artisan**

**Comment by mymocms** [comment]
This is a laravel package, you must install laravel before install it

**Comment by LeAnhTuan0810** [comment]
so i need to install the first one? https://laravel.com/docs/7.x/installation

**Comment by LeAnhTuan0810** [comment]
First I go to "cmd" using the command "composer require mymocms/mymocms" 
and it created mymocms folder, then I copied the items inside the folder, pasted it into the htdocs folder
![Untitled](https://user-images.githubusercontent.com/77945073/126163272-8ead86bd-5c6d-4404-b46d-7db8884fd7b3.png)

**Comment by LeAnhTuan0810** [comment]
@mymocms
